DELETE  http://localhost:3003/api/user
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjYwNzIwMjgwMjBhODgzMjgxOGExMGRkYyIsInVzZXJuYW1lIjoiTWFyY29FbERlbEFyY28iLCJpYXQiOjE2MTgwODQ0OTUsImV4cCI6MTYxOTM4MDQ5NX0.cKJ6532S7rsNj-x9JOClLnbIj_feCScPrwXsb2DqpAA

{
 "username":"MarcoElDelArco",
 "password":"61651165161"
}